version: "2"
services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    working_dir: /var/www
    volumes_from:
      - php
    ports:
      - 8000:80
  database:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=desafio"
      - "MYSQL_USER=desafio"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"